zuul:
  prefix: /api
  routes:
    eureka-client:
      path: /server/**
      url: http://localhost:8071
    config-server-client:
      path: /client/**
      serviceId: config-server-client
    


spring:
  application:
    name: zuul-gateway
    
server:
  port: 8073
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      
    
    